name: HENEN APK Yapici
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apk-yap:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Java Kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gereksinimleri Yükle
        run: |
          pip install flet
          pip install -r HENEN/requirements.txt

      - name: APK Oluştur
        run: |
          flet build apk HENEN --no-ios-pod-install

      - name: APK Dosyasını Kaydet
        uses: actions/upload-artifact@v3
        with:
          name: HENEN-APK
          path: build/app/outputs/flutter-apk/app-release.apk
